task: "vqav2_testdev"
include: _default_template_vqav2_yaml
test_split: testdev
metric_list:
  - metric: submission
    aggregation: !function utils.vqav2_aggreate_submissions
    higher_is_better: true
process_results: !function utils.vqav2_process_results_test
